(function(){'use strict';
var $=function(s){return document.querySelector(s)},T=window.THREE;
var status=$('#renderStatus');
function finishIntro(){var intro=$('#cinematicIntro');if(!intro||intro.classList.contains('leaving'))return;intro.classList.add('leaving');introActive=false;document.body.classList.remove('intro-playing');document.body.classList.add('intro-ended','camera-handoff');setTimeout(function(){if(intro.parentNode)intro.parentNode.removeChild(intro);document.body.classList.remove('intro-ended');resize();markDirty();},1250);setTimeout(function(){window.scrollTo({top:0,behavior:'auto'});},60);setTimeout(function(){document.body.classList.remove('camera-handoff');},1600);markDirty();}
function fail(message){status.classList.remove('ready');status.textContent=message;status.style.pointerEvents='auto';var intro=$('#cinematicIntro');if(intro){intro.classList.add('leaving');document.body.classList.remove('intro-playing');setTimeout(function(){intro.remove();},1200);}}
var skip=$('#skipIntro');if(skip)skip.addEventListener('click',finishIntro);window.addEventListener('keydown',function(e){if(e.key==='Escape')finishIntro();});
if(!T){fail('3D-движок не запустился в предпросмотре. Скачай HTML и открой его в Chrome, Edge или Firefox.');return;}
var canvas=$('#scene'),renderer,scene,camera,planet,world,rings,ringMat,rocks,atmosphere,core,moons=[],keyLight,rimLight;
var reduced=window.matchMedia('(prefers-reduced-motion:reduce)'),chapters=Array.from(document.querySelectorAll('.chapter')),links=Array.from(document.querySelectorAll('.timeline a'));
var target=0,progress=0,selected=null,dragQ=null,ringsEnabled=true,cutOverride=null,lightMode='warm',ready=false,dirty=true,cut=0,ringAmount=1,lastScroll=window.scrollY,prev=0,introActive=true,introZoom=2.8,rafId=0,frameTimes=[],quality='balanced',pageHidden=false;
var smallScreen=window.matchMedia('(max-width: 700px)').matches;
var lowPower=smallScreen||navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4||navigator.deviceMemory&&navigator.deviceMemory<=4||navigator.connection&&navigator.connection.saveData;
quality=lowPower?'low':(navigator.hardwareConcurrency>=8&&window.devicePixelRatio<=2?'high':'balanced');
function wake(){if(!rafId&&renderer&&!pageHidden)rafId=requestAnimationFrame(animate);}
function markDirty(){dirty=true;wake();}
document.documentElement.dataset.quality=quality;
var seed=1401;function rand(){seed=seed*16807%2147483647;return(seed-1)/2147483646;}
function smooth(a,b,x){var t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t);}
function hash(x,y,z){var s=Math.sin(x*127.1+y*311.7+z*74.7)*43758.5453123;return s-Math.floor(s);}
function noise(x,y,z){var ix=Math.floor(x),iy=Math.floor(y),iz=Math.floor(z),fx=x-ix,fy=y-iy,fz=z-iz;fx=fx*fx*(3-2*fx);fy=fy*fy*(3-2*fy);fz=fz*fz*(3-2*fz);function mix(a,b,t){return a*(1-t)+b*t;}return mix(mix(mix(hash(ix,iy,iz),hash(ix+1,iy,iz),fx),mix(hash(ix,iy+1,iz),hash(ix+1,iy+1,iz),fx),fy),mix(mix(hash(ix,iy,iz+1),hash(ix+1,iy,iz+1),fx),mix(hash(ix,iy+1,iz+1),hash(ix+1,iy+1,iz+1),fx),fy),fz);}
function fbm(x,y,z){return noise(x,y,z)*.57+noise(x*2.1+7,y*2.1,z*2.1)*.28+noise(x*4.2,y*4.2+6,z*4.2)*.15;}
function makeCraterMesh(radius,segments,rows,count,palette){
 var geo=new T.SphereGeometry(radius,segments,rows),position=geo.attributes.position,color=[];
 var craters=[{x:.30,y:.22,z:Math.sqrt(1-.3*.3-.22*.22),r:.245,d:.060},{x:-.46,y:-.25,z:Math.sqrt(1-.46*.46-.25*.25),r:.15,d:.034},{x:.57,y:-.41,z:Math.sqrt(1-.57*.57-.41*.41),r:.11,d:.031}];
 for(var c=0;c<count;c++){var y=rand()*2-1,a=rand()*Math.PI*2,l=Math.sqrt(1-y*y),r=.040+Math.pow(rand(),2)*.17;craters.push({x:Math.cos(a)*l,y:y,z:Math.sin(a)*l,r:r,d:r*.22});}
 var dir=new T.Vector3(),col=new T.Color(),dark=new T.Color(palette[0]),sand=new T.Color(palette[1]),ash=new T.Color(palette[2]);
 for(var i=0;i<position.count;i++){dir.fromBufferAttribute(position,i).normalize();var x=dir.x,y=dir.y,z=dir.z,n=fbm(x*5+12,y*5-7,z*5+3),ridge=1-Math.abs(2*noise(x*17,y*17,z*17)-1),height=(n-.5)*.021+Math.pow(ridge,7)*.006,rim=0,bowl=0;
 for(var k=0;k<craters.length;k++){var cr=craters[k],dot=x*cr.x+y*cr.y+z*cr.z;if(dot<Math.cos(cr.r*1.4))continue;var d=Math.acos(Math.min(1,dot))/cr.r;if(d<1){var well=-cr.d*Math.pow(1-d*d,2);height+=well;bowl=Math.max(bowl,(1-d)*.7);if(cr.r>.17)height+=cr.d*.18*Math.exp(-d*d/.035);}var edge=Math.exp(-Math.pow((d-1)/.12,2))*cr.d*.50;height+=edge;rim=Math.max(rim,edge*14);}
 position.setXYZ(i,x*radius*(1+height),y*radius*(1+height),z*radius*(1+height));
 var m=smooth(.29,.7,n);col.copy(dark).lerp(sand,m*.9).lerp(ash,Math.max(0,Math.abs(y)-.65)*.55);col.multiplyScalar(1-bowl*.42).lerp(sand,Math.min(.3,rim));color.push(col.r,col.g,col.b);}
 geo.setAttribute('color',new T.Float32BufferAttribute(color,3));geo.computeVertexNormals();geo.computeBoundingSphere();return geo;
}
function grainTexture(){var c=document.createElement('canvas');c.width=512;c.height=256;var ctx=c.getContext('2d'),im=ctx.createImageData(c.width,c.height);for(var i=0;i<im.data.length;i+=4){var x=(i/4)%512,y=Math.floor(i/4/512),v=Math.floor(205+rand()*42+Math.sin(x*.39+y*.61)*6);im.data[i]=im.data[i+1]=im.data[i+2]=v;im.data[i+3]=255;}ctx.putImageData(im,0,0);var tex=new T.CanvasTexture(c);tex.wrapS=T.RepeatWrapping;tex.wrapT=T.RepeatWrapping;tex.repeat.set(6,4);return tex;}
var poses=[{x:.06,y:-.12,z:-.10,d:6.55},{x:.24,y:1.05,z:-.07,d:4.80},{x:-.36,y:2.25,z:.32,d:6.6},{x:.06,y:3.35,z:-.09,d:5.1},{x:.30,y:4.75,z:-.16,d:7.30},{x:.12,y:6.28,z:-.10,d:6.1}];
var views={global:{x:.06,y:-.12,z:-.10,d:6.55,title:'Орбитальный обзор',text:'Планета, кольца и спутники в одной объёмной сцене.'},surface:{x:.05,y:.18,z:0,d:4.8,title:'Поверхность',text:'Кратерный рельеф сформирован геометрией, а не нарисован поверх шара.'},rings:{x:-.42,y:2.25,z:.22,d:6.6,title:'Система колец',text:'Полосы, промежутки, каменные фрагменты и тени.'},core:{x:0,y:3.35,z:0,d:5.1,title:'Внутреннее строение',text:'Художественный разрез вымышленной планеты: кора, мантия и ядро.'},moons:{x:.3,y:4.75,z:-.16,d:7.3,title:'Планета и спутники',text:'Движение двух спутников привязано к положению страницы.'}};
function scrollState(){var offsets=chapters.map(function(c){return c.offsetTop;}),y=window.scrollY,i=0;while(i<4&&y>=offsets[i+1])i++;target=i+Math.max(0,Math.min(1,(y-offsets[i])/(offsets[i+1]-offsets[i])));if(y>=offsets[5])target=5;var chapter=Math.min(5,Math.floor(target+.4));links.forEach(function(a,n){a.classList.toggle('active',n===chapter);});$('#timelineFill').style.width=target/5*100+'%';$('#progressText').textContent=Math.round(target/5*100)+'%';$('#sceneCaption').textContent=['ПЕРВЫЙ КОНТАКТ','РЕЛЬЕФ / КРАТЕРЫ И ХРЕБТЫ','КОЛЬЦА / ОРБИТАЛЬНАЯ СИСТЕМА','ВНУТРИ ПЛАНЕТЫ / РАЗРЕЗ','AURELIA / NYX / IO','ОБСЕРВАТОРИЯ'][chapter];markDirty();}
window.addEventListener('scroll',function(){if(Math.abs(window.scrollY-lastScroll)>4){selected=null;dragQ=null;cutOverride=null;$('#tooltip').hidden=true;}lastScroll=window.scrollY;scrollState();},{passive:true});window.addEventListener('resize',function(){scrollState();resize();});scrollState();
$('#menuButton').addEventListener('click',function(){var open=$('#menu').hidden;$('#menu').hidden=!open;this.setAttribute('aria-expanded',String(open));});$('#menu').addEventListener('click',function(e){if(e.target.closest('a')){$('#menu').hidden=true;$('#menuButton').setAttribute('aria-expanded','false');}});window.addEventListener('keydown',function(e){if(e.key==='Escape'){$('#menu').hidden=true;$('#menuButton').setAttribute('aria-expanded','false');}});
function selectView(name){selected=views[name]||views.global;dragQ=null;cutOverride=name==='core'?1:0;$('#viewSelect').value=name;$('#selectedTitle').textContent=selected.title;$('#selectedDescription').textContent=selected.text;$('#tooltip').textContent=selected.title;$('#tooltip').hidden=false;markDirty();}
$('#viewSelect').addEventListener('change',function(){selectView(this.value);});document.querySelectorAll('[data-view]').forEach(function(b){b.addEventListener('click',function(){selectView(b.dataset.view);});});
function toggleRings(){ringsEnabled=!ringsEnabled;$('#ringButton').setAttribute('aria-pressed',String(ringsEnabled));$('#ringButton').innerHTML='Кольца <span>'+(ringsEnabled?'●':'-')+'</span>';document.querySelectorAll('[data-toggle-rings]').forEach(function(b){b.innerHTML=(ringsEnabled?'Сравнить с видом без колец':'Вернуть кольца')+' <span>↗</span>';});markDirty();}
$('#ringButton').addEventListener('click',toggleRings);document.querySelectorAll('[data-toggle-rings]').forEach(function(b){b.addEventListener('click',toggleRings);});$('#cutButton').addEventListener('click',function(){cutOverride=cut>.5?0:1;markDirty();});$('#resetButton').addEventListener('click',function(){selected=null;dragQ=null;cutOverride=null;ringsEnabled=true;$('#ringButton').setAttribute('aria-pressed','true');$('#ringButton').innerHTML='Кольца <span>●</span>';$('#tooltip').hidden=true;$('#viewSelect').value='global';markDirty();});
function light(mode){lightMode=mode;if(keyLight){keyLight.color.set(mode==='warm'?0xffe6c9:0xd9e8ff);rimLight.color.set(mode==='warm'?0x7aafe0:0x807fff);keyLight.intensity=mode==='warm'?3.6:4.1;}$('#warmButton').setAttribute('aria-pressed',String(mode==='warm'));$('#coldButton').setAttribute('aria-pressed',String(mode==='cold'));markDirty();}
$('#warmButton').addEventListener('click',function(){light('warm');});$('#coldButton').addEventListener('click',function(){light('cold');});
function resize(){if(!renderer)return;var stage=$('#stage'),w=stage.clientWidth,h=stage.clientHeight;var cap=quality==='low'?.85:quality==='balanced'?1.2:1.5;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,cap));renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();markDirty();}
function qFor(p){return new T.Quaternion().setFromEuler(new T.Euler(p.x,p.y,p.z,'YXZ'));}
var clipPlane=new T.Plane(new T.Vector3(.4618,0,-.887),3),bump;
function init(){try{
 renderer=new T.WebGLRenderer({canvas:canvas,antialias:quality!=='low',alpha:true,powerPreference:quality==='high'?'high-performance':'low-power',preserveDrawingBuffer:false,stencil:false,depth:true});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.localClippingEnabled=true;renderer.shadowMap.enabled=quality==='high'&&!smallScreen;renderer.shadowMap.type=T.PCFSoftShadowMap;
 scene=new T.Scene();camera=new T.PerspectiveCamera(42,1,.1,70);camera.position.set(0,0,9.35);resize();world=new T.Group();scene.add(world);bump=grainTexture();
 var planetMat=new T.MeshStandardMaterial({vertexColors:true,roughness:.96,metalness:.005,map:bump,bumpMap:bump,bumpScale:.003,clippingPlanes:[clipPlane],clipShadows:true});
 planet=new T.Mesh(makeCraterMesh(1.19,quality==='low'?112:quality==='balanced'?176:288,quality==='low'?72:quality==='balanced'?112:192,quality==='low'?48:quality==='balanced'?82:138,[0x292e35,0x938b7f,0xc1b9a8]),planetMat);planet.castShadow=planet.receiveShadow=true;world.add(planet);
 atmosphere=new T.Mesh(new T.SphereGeometry(1.275,96,64),new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{strength:{value:.52}},vertexShader:'varying vec3 n;varying vec3 v;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'precision mediump float;varying vec3 n;varying vec3 v;uniform float strength;void main(){float r=pow(1.-max(dot(normalize(n),normalize(v)),0.),4.);gl_FragColor=vec4(.20,.46,.70,r*strength);}'}));world.add(atmosphere);
 rings=new T.Group();rings.rotation.x=1.03;world.add(rings);
 ringMat=new T.MeshStandardMaterial({color:0xc0b7a5,roughness:.92,metalness:.04,transparent:true,opacity:.86,side:T.DoubleSide,depthWrite:true});
 ringMat.onBeforeCompile=function(s){s.vertexShader='varying vec2 vRing;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvRing=position.xy;');s.fragmentShader='varying vec2 vRing;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\nfloat r=length(vRing);float bands=.55+.45*sin(r*285.);float coarse=.65+.35*sin(r*43.);float gap=1.-smoothstep(.035,.019,abs(r-1.86));if(abs(r-1.86)<.019||abs(r-2.015)<.008)discard;diffuseColor.rgb*=.5+bands*.32+coarse*.22;diffuseColor.a*=.58+bands*.42;');};
 var ringMesh=new T.Mesh(new T.RingGeometry(1.52,2.13,256,20),ringMat);ringMesh.castShadow=false;ringMesh.receiveShadow=true;rings.add(ringMesh);
 var rocky=new T.MeshStandardMaterial({color:0x8a776a,roughness:1,metalness:0});var rockCount=quality==='low'?180:quality==='balanced'?520:1250;rocks=new T.InstancedMesh(new T.IcosahedronGeometry(1,quality==='low'?0:1),rocky,rockCount);var temp=new T.Object3D();for(var i=0;i<rockCount;i++){var a=rand()*Math.PI*2,r=2.13+rand()*.19,size=.002+Math.pow(rand(),4)*.012;temp.position.set(Math.cos(a)*r,Math.sin(a)*r,(rand()-.5)*.028);temp.rotation.set(rand()*6,rand()*6,rand()*6);temp.scale.set(size,size*.6,size*.8);temp.updateMatrix();rocks.setMatrixAt(i,temp.matrix);}rocks.instanceMatrix.needsUpdate=true;rings.add(rocks);
 // Внутренние слои — отдельные тела и объёмные борта, не текстура разреза.
 core=new T.Group();core.rotation.y=-.48;scene.add(core);var layerData=[[.78,1.12,0x603229,.12],[.47,.78,0xcc6632,.25],[.0,.47,0xffbe64,.8]];
 layerData.forEach(function(l,j){var shape=new T.Shape();shape.absarc(0,0,l[1],0,Math.PI*2,false);if(l[0]>0){var hole=new T.Path();hole.absarc(0,0,l[0],0,Math.PI*2,true);shape.holes.push(hole);}var geo=new T.ExtrudeGeometry(shape,{depth:.23+(.05*j),bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.018,bevelThickness:.015,curveSegments:96});var mat=new T.MeshStandardMaterial({color:l[2],emissive:l[2],emissiveIntensity:l[3],roughness:.84,metalness:.025,bumpMap:bump,bumpScale:.004,transparent:true,opacity:0});var mesh=new T.Mesh(geo,mat);mesh.position.z=.025+j*.04;core.add(mesh);mat.onBeforeCompile=function(s){s.vertexShader='varying vec3 vLayer;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvLayer=position;');s.fragmentShader='varying vec3 vLayer;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\nfloat swirl=sin(vLayer.x*38.+sin(vLayer.y*17.)*4.)*sin(vLayer.y*31.+cos(vLayer.x*24.)*3.);diffuseColor.rgb*=.80+.20*swirl;totalEmissiveRadiance*=.82+.18*swirl;');};var border=new T.Mesh(new T.TorusGeometry(l[1],.012,8,128),new T.MeshStandardMaterial({color:0xe8a264,emissive:0x552100,emissiveIntensity:.5,transparent:true,opacity:0}));border.position.z=.27+j*.09;core.add(border);});
 var coreBall=new T.Mesh(new T.SphereGeometry(.435,64,48),new T.MeshStandardMaterial({color:0xf6b95a,emissive:0xb35115,emissiveIntensity:.32,roughness:.75,metalness:.035,bumpMap:bump,bumpScale:.004,transparent:true,opacity:0}));coreBall.position.z=.33;core.add(coreBall);
 var satelliteData=[{r:.16,orbit:2.50,phase:.90,speed:1.18,incl:.30,palette:[0x414856,0x8a959b,0xa8a9a7],name:'NYX'},{r:.085,orbit:2.33,phase:2.1,speed:-1.63,incl:-.48,palette:[0x5a4540,0xbd9368,0x918676],name:'IO'}];satelliteData.forEach(function(info,i){var mat=new T.MeshStandardMaterial({vertexColors:true,roughness:1,bumpMap:bump,bumpScale:.0015});var moon=new T.Mesh(makeCraterMesh(info.r,quality==='low'?40:quality==='balanced'?64:96,quality==='low'?28:quality==='balanced'?42:64,quality==='low'?12:quality==='balanced'?22:36,info.palette),mat);moon.castShadow=moon.receiveShadow=true;moon.userData=info;scene.add(moon);moons.push(moon);});
 scene.add(new T.HemisphereLight(0xc4d3e3,0x211b17,.72));keyLight=new T.DirectionalLight(0xffe6c9,3.4);keyLight.position.set(-4,5,6);keyLight.castShadow=renderer.shadowMap.enabled;keyLight.shadow.mapSize.set(quality==='high'?1024:512,quality==='high'?1024:512);keyLight.shadow.camera.left=keyLight.shadow.camera.bottom=-3.5;keyLight.shadow.camera.right=keyLight.shadow.camera.top=3.5;keyLight.shadow.normalBias=.015;keyLight.shadow.bias=-.0002;scene.add(keyLight);rimLight=new T.DirectionalLight(0x7aafe0,2.3);rimLight.position.set(3,.2,-2);scene.add(rimLight);
 var stars=[],colors=[],starColor=new T.Color();for(var j=0,starCount=quality==='low'?180:quality==='balanced'?360:650;j<starCount;j++){stars.push((rand()-.5)*50,(rand()-.5)*35,-12-rand()*18);starColor.setHSL(.58+rand()*.05,.12,.35+rand()*.4);colors.push(starColor.r,starColor.g,starColor.b);}var sg=new T.BufferGeometry();sg.setAttribute('position',new T.Float32BufferAttribute(stars,3));sg.setAttribute('color',new T.Float32BufferAttribute(colors,3));scene.add(new T.Points(sg,new T.PointsMaterial({vertexColors:true,size:.024,transparent:true,opacity:.6,sizeAttenuation:true})));
 world.quaternion.copy(qFor(poses[0]));ready=true;document.body.classList.add('js-running');var io=new IntersectionObserver(function(es){es.forEach(function(e){e.target.classList.toggle('visible',e.isIntersecting);});},{threshold:.08});document.querySelectorAll('.reveal').forEach(function(e){io.observe(e);});
 renderer.render(scene,camera);status.classList.add('ready');canvas.addEventListener('webglcontextlost',function(e){e.preventDefault();pageHidden=true;fail('Графический контекст был сброшен. Перезагрузи страницу или выбери более лёгкий режим графики.');});document.addEventListener('visibilitychange',function(){pageHidden=document.hidden;if(!pageHidden){prev=0;markDirty();}});if(reduced.matches){finishIntro();}else{setTimeout(function(){var el=$('#introStatus');if(el)el.textContent='СИГНАЛ УСТАНОВЛЕН / AURELIA';},650);setTimeout(finishIntro,4700);}wake();
}catch(e){console.error(e);fail('3D не удалось запустить: '+e.message+'. Попробуй открыть скачанный HTML в браузере с WebGL.');}}
function animate(time){rafId=0;if(pageHidden||!renderer)return;var dt=prev?Math.min((time-prev)/1000,.08):.016;prev=time;
 if(dt>0.035&&quality==='high'){frameTimes.push(dt);if(frameTimes.length>24)frameTimes.shift();if(frameTimes.length===24&&frameTimes.reduce(function(a,b){return a+b;},0)/24>.035){quality='balanced';document.documentElement.dataset.quality=quality;renderer.shadowMap.enabled=false;keyLight.castShadow=false;resize();frameTimes=[];}}var ease=reduced.matches?1:1-Math.exp(-dt*7);progress+=(target-progress)*ease;var i=Math.min(4,Math.floor(progress)),t=smooth(0,1,progress-i),a=poses[i],b=poses[i+1],desired=qFor(a).slerp(qFor(b),t),distance=T.MathUtils.lerp(a.d,b.d,t);if(selected){desired.copy(qFor(selected));distance=selected.d;}if(dragQ)desired.copy(dragQ);
 var cutTarget=smooth(2.45,2.96,progress)*(1-smooth(3.45,3.96,progress));if(cutOverride!==null)cutTarget=cutOverride;
 var ringTarget=ringsEnabled?1:0;if((progress>.75&&progress<1.45)||(selected===views.surface)||cutTarget>.45)ringTarget=0;
 var zoomGoal=introActive&&!reduced.matches?2.8:0;introZoom+=(zoomGoal-introZoom)*(reduced.matches?1:1-Math.exp(-dt*(introActive?1.25:2.8)));var wantedDistance=distance*(window.innerWidth<700?1.06:1)+introZoom;var moving=Math.abs(target-progress)>.0001||world.quaternion.angleTo(desired)>.0001||Math.abs(camera.position.z-wantedDistance)>.0001||Math.abs(introZoom-zoomGoal)>.002||Math.abs(cut-cutTarget)>.0001||Math.abs(ringAmount-ringTarget)>.0001;
 world.quaternion.slerp(desired,ease);camera.position.z+=(wantedDistance-camera.position.z)*ease;cut+=(cutTarget-cut)*ease;ringAmount+=(ringTarget-ringAmount)*ease;clipPlane.constant=3*(1-cut);core.visible=cut>.02;core.children.forEach(function(m){m.material.opacity=smooth(.35,.9,cut);});atmosphere.material.uniforms.strength.value=.45*(1-cut*.9);rings.visible=ringAmount>.005;ringMat.opacity=.86*ringAmount;rocks.visible=ringAmount>.5;moons.forEach(function(m,n){var d=m.userData,angle=d.phase+progress*d.speed;m.position.set(Math.cos(angle)*d.orbit,Math.sin(angle)*d.incl,Math.sin(angle)*d.orbit*.62);m.rotation.y=progress*(n?-.6:1);m.visible=cut<.8&&distance>5.8;});
 $('#cutButton').setAttribute('aria-pressed',String(cut>.5));$('#cutButton').innerHTML='Разрез <span>'+(cut>.5?'●':'-')+'</span>';$('#coordinates').textContent='КАМЕРА / '+(camera.position.z).toFixed(2)+' U';$('#layerCaption').textContent=cut>.5?'ВНУТРЕННИЕ СЛОИ / ОБЪЁМНЫЙ РАЗРЕЗ':'РЕЛЬЕФ / НАСТОЯЩАЯ ГЕОМЕТРИЯ';
 if(moving||dirty){renderer.render(scene,camera);dirty=false;}window.aureliaState={ready:true,progress:progress,target:target,cut:cut,rings:ringAmount,light:lightMode,view:selected?selected.title:null,quaternion:world.quaternion.toArray(),vertices:planet.geometry.attributes.position.count,terrainRange:planet.geometry.boundingSphere.radius,quality:quality};if(moving||dirty||introActive)wake();}
var pointer=null,moved=false;canvas.addEventListener('pointerdown',function(e){if(!ready)return;pointer={x:e.clientX,y:e.clientY,q:world.quaternion.clone(),id:e.pointerId};moved=false;});canvas.addEventListener('pointermove',function(e){if(!pointer||!ready)return;var dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(e.pointerType==='touch'&&Math.abs(dy)>Math.abs(dx))return;if(Math.abs(dx)+Math.abs(dy)>8){moved=true;selected=null;dragQ=new T.Quaternion().setFromEuler(new T.Euler(dy*.004,dx*.005,0,'YXZ')).multiply(pointer.q);markDirty();}});window.addEventListener('pointerup',function(){pointer=null;});canvas.addEventListener('pointercancel',function(){pointer=null;});
// Обычный встроенный JavaScript: запуск не зависит от модулей, CDN и загрузки изображений.
init();
})();
